config/routes.rb
Rails.application.routes.draw do
  resources :railmicroposts
  resources :railusers
  resources :microposts
  resources :users

  root 'railusers#index'

end

app/models/railmicropost.rb
class Railmicropost < ActiveRecord::Base
    belongs_to :railuser
    validates :content, length: { maximum: 140 }
end

app/controllers/railmicroposts_controller.rb
class RailmicropostsController < ApplicationController
  before_action :set_railmicropost, only: [:show, :edit, :update, :destroy]

  # GET /railmicroposts
  # GET /railmicroposts.json
  def index
    @railmicroposts = Railmicropost.all
  end

  # GET /railmicroposts/1
  # GET /railmicroposts/1.json
  def show
  end

  # GET /railmicroposts/new
  def new
    @railmicropost = Railmicropost.new
  end

  # GET /railmicroposts/1/edit
  def edit
  end

  # POST /railmicroposts
  # POST /railmicroposts.json
  def create
    @railmicropost = Railmicropost.new(railmicropost_params)

    respond_to do |format|
      if @railmicropost.save
        format.html { redirect_to @railmicropost, notice: 'Railmicropost was successfully created.' }
        format.json { render :show, status: :created, location: @railmicropost }
      else
        format.html { render :new }
        format.json { render json: @railmicropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railmicroposts/1
  # PATCH/PUT /railmicroposts/1.json
  def update
    respond_to do |format|
      if @railmicropost.update(railmicropost_params)
        format.html { redirect_to @railmicropost, notice: 'Railmicropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @railmicropost }
      else
        format.html { render :edit }
        format.json { render json: @railmicropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railmicroposts/1
  # DELETE /railmicroposts/1.json
  def destroy
    @railmicropost.destroy
    respond_to do |format|
      format.html { redirect_to railmicroposts_url, notice: 'Railmicropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railmicropost
      @railmicropost = Railmicropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railmicropost_params
      params.require(:railmicropost).permit(:content, :user_id)
    end
end

app/helpers/railmicroposts_helper.rb
module RailmicropostsHelper
end

app/views/railmicroposts/_form.html.erb
<%= form_for(@railmicropost) do |f| %>
  <% if @railmicropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railmicropost.errors.count, "error") %> prohibited this railmicropost from being saved:</h2>

      <ul>
      <% @railmicropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railmicroposts/edit.html.erb
<h1>Editing Railmicropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @railmicropost %> |
<%= link_to 'Back', railmicroposts_path %>

app/views/railmicroposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Railmicroposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railmicroposts.each do |railmicropost| %>
      <tr>
        <td><%= railmicropost.content %></td>
        <td><%= railmicropost.user_id %></td>
        <td><%= link_to 'Show', railmicropost %></td>
        <td><%= link_to 'Edit', edit_railmicropost_path(railmicropost) %></td>
        <td><%= link_to 'Destroy', railmicropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railmicropost', new_railmicropost_path %>

app/views/railmicroposts/new.html.erb
<h1>New Railmicropost</h1>

<%= render 'form' %>

<%= link_to 'Back', railmicroposts_path %>

app/views/railmicroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @railmicropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @railmicropost.user_id %>
</p>

<%= link_to 'Edit', edit_railmicropost_path(@railmicropost) %> |
<%= link_to 'Back', railmicroposts_path %>