config/routes.rb
Rails.application.routes.draw do
  resources :railmicroposts
  resources :railusers
  resources :microposts
  resources :users

  root 'railusers#index'

end

app/models/railuser.rb
class Railuser < ActiveRecord::Base
    has_many :railmicroposts
end

app/controllers/railusers_controller.rb
class RailusersController < ApplicationController
  before_action :set_railuser, only: [:show, :edit, :update, :destroy]

  # GET /railusers
  # GET /railusers.json
  def index
    @railusers = Railuser.all
  end

  # GET /railusers/1
  # GET /railusers/1.json
  def show
  end

  # GET /railusers/new
  def new
    @railuser = Railuser.new
  end

  # GET /railusers/1/edit
  def edit
  end

  # POST /railusers
  # POST /railusers.json
  def create
    @railuser = Railuser.new(railuser_params)

    respond_to do |format|
      if @railuser.save
        format.html { redirect_to @railuser, notice: 'Railuser was successfully created.' }
        format.json { render :show, status: :created, location: @railuser }
      else
        format.html { render :new }
        format.json { render json: @railuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railusers/1
  # PATCH/PUT /railusers/1.json
  def update
    respond_to do |format|
      if @railuser.update(railuser_params)
        format.html { redirect_to @railuser, notice: 'Railuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @railuser }
      else
        format.html { render :edit }
        format.json { render json: @railuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railusers/1
  # DELETE /railusers/1.json
  def destroy
    @railuser.destroy
    respond_to do |format|
      format.html { redirect_to railusers_url, notice: 'Railuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railuser
      @railuser = Railuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railuser_params
      params.require(:railuser).permit(:name, :email)
    end
end

app/helpers/railusers_helper.rb
module RailusersHelper
end

app/views/railusers/_form.html.erb
<%= form_for(@railuser) do |f| %>
  <% if @railuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railuser.errors.count, "error") %> prohibited this railuser from being saved:</h2>

      <ul>
      <% @railuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railusers/edit.html.erb
<h1>Editing Railuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @railuser %> |
<%= link_to 'Back', railusers_path %>

app/views/railusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Railusers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railusers.each do |railuser| %>
      <tr>
        <td><%= railuser.name %></td>
        <td><%= railuser.email %></td>
        <td><%= link_to 'Show', railuser %></td>
        <td><%= link_to 'Edit', edit_railuser_path(railuser) %></td>
        <td><%= link_to 'Destroy', railuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railuser', new_railuser_path %>

app/views/railusers/new.html.erb
<h1>New Railuser</h1>

<%= render 'form' %>

<%= link_to 'Back', railusers_path %>

app/views/railusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @railuser.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @railuser.email %>
</p>

<%= link_to 'Edit', edit_railuser_path(@railuser) %> |
<%= link_to 'Back', railusers_path %>